name: Requirement
description: "Requirement"
labels: ["requirement"]
title: "[REQ] "
body:
  - type: dropdown
    id: risk-class
    attributes:
      label: Risk class
      description: What is risk classification of the requirement?
      options:
        - Unknown
        - Low
        - Medium
        - High
    validations:
      required: true
  - type: textarea
    id: requirement-spec
    attributes:
      label: Specification
  - type: textarea
    id: implemented-by
    attributes:
      label: Implemented by
      description: Enter the Software Component GitHub issue numbers which implements this requirement
      placeholder: "#1"
  - type: textarea
    id: tested-by
    attributes:
      label: Tested by
      description: Enter the Test Case GitHub issue numbers which validate this requirement
      placeholder: "#1"
